repos:

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
      language_version: python3.8

- repo: https://github.com/timothycrosley/isort
  rev: 5.2.0
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.1.0'
  hooks:
    - id: check-builtin-literals
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace

- repo: local
  hooks:
  - id: sort-json
    name: Sort theme.json
    language: python
    always_run: true
    entry: python tools/sort-json.py
